#%RAML 1.0
title: Rangle's Backend Starter
baseUri: https://api-koa-starter.rangleapp.io
mediaType: application/json
securitySchemes:
  none:
    type: x-none
    description: |
      Application currently does not include any authentication.
/demo: !include ../../src/routes/demo/demo.raml
/health: !include ../../src/routes/health-check/health-check.raml
