displayName: |
  Demo endpoints
description: |
  Some demo endpoints to show how various features work, including this documentation.
/foo-is-required:
  get:
    description: |
      Use is to demonstrate request validation is working as intended and forces params to be provided.
    queryParameters:
      foo:
        type: string
        required: true
        example: "bar"
    responses:
      200:
        body:
          application/json:
            example: |
              'It works!'
    securedBy: [none]
/foo-must-be-numeric:
  get:
    description: |
      Use is to demonstrate request validation is working as intended and enforces numeric content of params.
    queryParameters:
      foo:
        type: number
        required: true
        example: "123"
    responses:
      200:
        body:
          application/json:
            example: |
              'It works!'
    securedBy: [none]
